apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/install.yaml
  - argo-apps/argocd.yaml
  - argo-apps/motherofallapps.yaml

patches:
  - patches/argocd-server.yaml
  - patches/labels.yaml

namespace: argocd
