{{ if .Values.manageCerts }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard
  namespace: nginx-ingress
spec:
  secretName: wildcard-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.domain }}"
  commonName: "*.{{ .Values.domain }}"
{{ end }}