apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  source:
    path: apps/nginx-ingress
    repoURL: https://github.com/fullstaq-labs/argodemo.git
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
